export const typeTags = [
  'The Instigator',
  'The Co-Pilot',
  'The Curator',
  'The Lone Wolf',
  'The Seducer',
  'The Flirt',
  'The Tease',
  'The Ghost',
  'The Builder',
  'The Anchor',
  'The Gatekeeper',
  'The Passenger',
  'The Spark',
  'The Ride-Along',
  'The Explorer',
  'The Siren',
  'The Seeker',
  'The Nurturer',
  'The Companion',
  'The Estranged',
];
